### PR TITLE
Update Packet reference to Equinix Metal

### PR DESCRIPTION
**Pull request by taylorwaggoner**

### CODE REVIEW

**Comment by taylorwaggoner** [comment]
@caniszczyk

**Comment by solardiz** [comment]
Somehow the new Equinix Metal website doesn't list any ARM servers - this should ideally be clarified (with them, and in the update here).

**Comment by jacobsmith928** [comment]
Issue created to add previous generation servers to our docs:
https://github.com/packethost/docs/issues/105

**Comment by vielmetti** [comment]
@taylorwaggoner anything blocking this merge?

**Pull request merged**
